language: java
jdk:
  - oraclejdk8
os:
  - linux
notifications:
  email:
    - MateuszLorencki+Travis-CI@gmail.com
    - kluchus@gmail.com
    - nexo.1993@gmail.com
services:
    - mysql
before_install:
    - sed -i 's/spring.datasource.username =.*/spring.datasource.username = travis/g' src/main/resources/application.properties
    - sed -i 's/spring.datasource.password =.*/spring.datasource.password =/g' src/main/resources/application.properties
    - mysql -e 'CREATE DATABASE transport;'
